# auto generated by src\build\Compile-ModuleManefest.ps1 on 08/31/2023 13:52:26

# class file - src\psmodule.example\private\classes\model.ps1
$typeDefinition = @'

namespace PSModule.Example
{
    public class Model
    {
        public string Text {get; set;}
    }
}
'@


if (-not ("PSModule.Example.Model" -As [type] ))
{
    Add-Type -TypeDefinition $typeDefinition
}



# private function import
foreach ($function in (Get-ChildItem "$PSScriptRoot\private" -Filter "*.ps1" -Recurse -ErrorAction Ignore | Sort-Object -Property FullName ))
{
    Write-Verbose "Importing private file: '$($function.FullName)'"

    . $function.FullName
}


# public function import
foreach ($function in (Get-ChildItem "$PSScriptRoot\public" -Filter "*.ps1" -Recurse -ErrorAction Ignore | Sort-Object -Property FullName ))
{
    Write-Verbose "Importing public file: '$($function.FullName)'"

    . $function.FullName
}


